spring.application.name=market-app
#server.port=8091
server.servlet.context-path=/market-app/ap1
spring.profiles.active=dev
springdoc.swagger-ui.path=/swagger.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher